language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install pycryptodome
  - pip install pytuya
  - pip install tuyapower

# command to run tests
script:
  - python tests.py
